name: check-error-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-error-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build